version: '3.8'

services:
    laravel_frontend_app:
        build:
            args:
                user: laravel_frontend_user
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: laravel_frontend_app_image
        container_name: laravel_frontend_app
        restart: unless-stopped

      
        working_dir: /var/www
        volumes:
            -   ./:/var/www
        networks:
            - laravel_network
    laravel_frontend_webserver:
        image: nginx:alpine
        container_name: laravel_frontend_webserver_container
        restart: unless-stopped
        ports:
            - "6161:80"

        depends_on:
            -   laravel_frontend_app
       
        volumes:
            -   ./:/var/www
            - ./docker-compose/nginx/:/etc/nginx/conf.d
        networks:
            - laravel_network




networks:
    laravel_network:
        driver: bridge
        name: laravel_network
        external: true
    
